version: 2
jobs:
  build:
    working_directory: /twitlib
    docker:
      - image: docker:18.06.3-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/twitlib.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/twitlib.tar | true
      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=twitlib -t twitlib ./twitlib
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/twitlib.tar twitlib
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/twitlib.tar
      - run:
          name: Run tests
          command: |
            docker run twitlib pytest /test
