version: 2.1

orbs:
  docker: circleci/docker@0.5.0
  codecov: codecov/codecov@1.0.4

jobs:

  build_and_test:
    executor: docker/machine
    steps:
      - checkout
      - docker/check
      - docker/build:
          image: tidalpaladin/twitlib
          tag: test
      - run:
          name: Run tests
          command: |
            set +o pipefail
            docker rm twitlib-test | true
            docker run --name=twitlib-test twitlib
      - run:
          name: Copy coverage.xml artifact
          command: |
            docker cp twitlib-test:/cov/coverage.xml ./
      - persist_to_workspace:
          root: workspace
          paths:
            - coverage.xml

  coverage_upload:
    machine: true
    steps:
      - codecov/upload:
          file: coverage.xml


workflows:
  build:
    jobs:
      - build_and_test
      - coverage_upload:
          requires:
            - build_and_test

  build_and_publish:
    jobs:
      - build_and_test
      - coverage_upload:
          requires:
            - build_and_test
      - docker/publish:
          requires:
            - build_and_test
          image: tidalpaladin/twitlib
          tag: stable
          filters:
            branches:
              only:
                - master
