version: 2
jobs:
  build:
    working_directory: /twitlib
    docker:
      - image: docker:18.06.3-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache py-pip=18.1-r0
            pip install codecov==2.0.15
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/twitlib.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/twitlib.tar | true
      - run:
          name: Build application Docker image
          command: |
            docker build \
              --cache-from=twitlib  \
              --tag twitlib \
              --target test \
              --build-arg cache=$(date +%Y-%m-%d:%H%M:%s)  \
              ./twitlib
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/twitlib.tar twitlib
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/twitlib.tar
      - run:
          name: Run tests
          command: |
            docker run -v ./:/cov twitlib
      - run:
          name: Upload codecov report
          command: |
            bash <(curl -s https://codecov.io/bash)
